### PR TITLE
[DNM] On add behaviour

### PR DESCRIPTION
**Pull request by kneemer**

### CODE REVIEW

**Comment by jgravois** [comment]
i see appropriate behavior with simple marker symbol points even when i get rid of the call to `_addPointLayer()` entirely.  is that weird? is that logic only for more complex renderers?

```js
this.metadata(function (error, response) {
    ...
    // if (this._loadedMap) {
    //   oldOnAdd(this._loadedMap);
    //   this._addPointLayer(this._loadedMap);
    // }
  }, this);

  this.onAdd = function (map) {
    this._loadedMap = map;
    oldOnAdd(this._loadedMap);
    // if (this._metadataLoaded) {
    //   this._addPointLayer(this._loadedMap);
    // }
  };
```
the simplified code seems appropriate to me.  binding to `this.onAdd` is all that should be necessary to ensure that the parent class initialization logic fires and the layer draws on the map.  you shouldn't have to call the same method manually.

with regard to `_addPointLayer()`, we should probably be allowing users to control ordering themselves (via panes) instead of bringing point layers [to the front](https://github.com/Esri/esri-leaflet-renderers/blob/master/src/FeatureLayerHook.js#L60) ourselves anyway...

**Comment by kneemer** [comment]
The addPointLayer is specifically for rendering the polygons with centroids.  It is an additional layer that is being added.  It could probably be done differently now but we needed two feature layers to represent it.

**Comment by kneemer** [comment]
The bring to front was the only way to ensure the centroids were on top in the past.

**Comment by jgravois** [comment]
okay.  thanks for clarifying.  i'm more than happy to leave that be.

**Pull request closed without merging**
